"""Node factory for LangGraph pipeline execution."""
import logging
from pathlib import Path
from typing import Callable, Dict, Any

from config import setup_logger, Config
from orchestrator.schema import SecurityState, AgentResult
from orchestrator.opencode_client import OpenCodeClient
from orchestrator.agent_config import AGENT_IO

log = setup_logger("nodes")


def _build_prompt(agent_name: str, state: SecurityState, base_prompt: str) -> str:
    """Builds the full prompt injecting knowledge base, context files, and output instructions."""
    io_config = AGENT_IO.get(agent_name, {})
    scan_dir = Path(state["scan_output_dir"])
    
    full_prompt = base_prompt + "\n\n"
    
    # Instruct node about repository and output paths
    if agent_name == "ingest":
        # Ingest runs inside repo_path; must save outputs to scan_output_dir
        full_prompt += (
            f"Your current working directory IS the repository to analyze.\n"
            f"You MUST save ALL output files (such as fingerprint.md) to this absolute path: {state['scan_output_dir']}\n"
            "You MUST NOT modify any existing repository files.\n\n"
        )
    else:
        # Analysis/aggregator agents run inside repo_path to bypass sandbox restrictions
        full_prompt += (
            f"The repository under review is your current working directory.\n"
            f"You will find context files generated by previous agents (like fingerprint.md) at this absolute path: {state['scan_output_dir']}\n"
            f"You MUST save your output files to the same absolute path: {state['scan_output_dir']}\n"
            "You MUST NOT modify the repository code or create files directly in the repository root.\n\n"
        )
    
    # Inject Knowledge Base files for analysis agents (not ingest)
    if agent_name != "ingest":
        owasp_file = Config.KNOWLEDGE_PATH / "owasp_top10_2025.md"
        sbd_file = Config.KNOWLEDGE_PATH / "secure_by_design.md"
        
        if owasp_file.exists():
            full_prompt += f"### Knowledge Base: OWASP Top 10 (2025)\n{owasp_file.read_text(encoding='utf-8')}\n\n"
        if sbd_file.exists():
            full_prompt += f"### Knowledge Base: Secure by Design\n{sbd_file.read_text(encoding='utf-8')}\n\n"
    
    # FIX #1: Inject context files from previous agents
    context_files = io_config.get("context_files", [])
    for ctx_file_name in context_files:
        ctx_path = scan_dir / ctx_file_name
        if ctx_path.exists():
            content = ctx_path.read_text(encoding="utf-8")
            full_prompt += f"### Context: {ctx_file_name}\n{content}\n\n"
        else:
            log.warning(f"Context file not found (skipped): {ctx_file_name}")
            
    # Instruct about output format from config
    instruction = io_config.get("output_instruction", "")
    if instruction:
        full_prompt += f"### Tasks & Output Instructions\n{instruction}\n\n"
        
    return full_prompt


def _read_ingest_outputs(scan_dir: Path) -> dict:
    """Read fingerprint and file manifest produced by the ingest agent."""
    updates: Dict[str, str] = {}
    
    fingerprint_path = scan_dir / "fingerprint.md"
    if fingerprint_path.exists():
        updates["fingerprint"] = fingerprint_path.read_text(encoding="utf-8")
        # In the new architecture, fingerprint also contains the file manifest
        updates["file_manifest"] = "Merged into fingerprint.md"
    
    return updates


def create_node_wrapper(agent_name: str, prompt_file: Path) -> Callable[[SecurityState], Dict[str, Any]]:
    """Creates a LangGraph node function for the specific agent based on OpenCode."""
    
    def node_fn(state: SecurityState) -> Dict[str, Any]:
        log.info(f"[{agent_name.upper()}] Starting execution...")
        
        # Check circuit-breaker: skip if a previous critical agent failed
        if state.get("stop_requested", False):
            log.warning(f"[{agent_name.upper()}] Skipped — pipeline stop was requested.")
            return {
                "current_agent": agent_name,
                "errors": [f"[{agent_name.upper()}] Skipped due to pipeline stop."],
            }
        
        # Read base prompt from .md file
        if prompt_file.exists():
            base_prompt = prompt_file.read_text(encoding="utf-8")
        else:
            base_prompt = f"You are the {agent_name} agent."
            log.warning(f"Prompt file not found for agent: {agent_name}. Using fallback prompt.")
            
        full_prompt = _build_prompt(agent_name, state, base_prompt)
        
        # Execute via OpenCode — all agents now run inside repo_path to avoid sandbox rejections
        client = OpenCodeClient()
        working_dir = state["repo_path"]
        result_dict = client.execute_prompt(full_prompt, 
                                            working_dir=working_dir,
                                            agent_name=agent_name)
        
        # Build AgentResult as plain dict (TypedDict-compatible)
        agent_result: AgentResult = {
            "success": result_dict["success"],
            "duration": result_dict["duration"],
            "output": result_dict["output"],
            "error": result_dict["error"],
        }
        
        # FIX #3: Return partial state update (no in-place mutation)
        state_update: Dict[str, Any] = {
            "current_agent": agent_name,
            "agent_outputs": {agent_name: agent_result},
        }
        
        if agent_result["success"]:
            state_update["completed_steps"] = [agent_name]
            log.info(f"[{agent_name.upper()}] Done ({agent_result['duration']:.1f}s)")
            
            # FIX #8: Populate fingerprint/file_manifest after ingest
            if agent_name == "ingest":
                ingest_data = _read_ingest_outputs(Path(state["scan_output_dir"]))
                state_update.update(ingest_data)
        else:
            err_msg = f"[{agent_name.upper()}] Failed: {agent_result['error']}"
            state_update["errors"] = [err_msg]
            # Circuit-breaker: stop pipeline if ingest fails (downstream agents need its output)
            if agent_name == "ingest":
                state_update["stop_requested"] = True
                log.error(f"{err_msg} — Pipeline will stop.")
            else:
                log.error(err_msg)
            
        return state_update
        
    return node_fn
